# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: WSO2 Identity Server Documentation
site_description: Documentation for WSO2 Identity Server
site_author: WSO2
site_url: https://wso2.com/identity-and-access-management/

# Repository
repo_name: wso2/docs-is
repo_url: https://github.com/wso2/docs-is
edit_uri: https://github.com/wso2/docs-is/edit/5.9.0/en/docs/

# Copyright
copyright: WSO2 Identity Server - Documentation

# Configuration
theme: material
theme:
  name: material
  palette:
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: 'en'

# Navigation
nav:
  - 'Home': index.md
  - 'Quick Starts':
      - 'Overview': quick-starts/overview.md
      - 'Mobile':
          - 'Android': quick-starts/android.md
          - 'iOS': quick-starts/ios.md
      - 'Frontend':
          - 'Angular': quick-starts/angular.md
          - 'React': quick-starts/react.md
      - 'Backend':
          - 'Java': quick-starts/java.md
          - 'NodeJs': quick-starts/nodejs.md
  - 'Guides':
      - 'Get Started': guides/before-you-start.md
      - 'Authentication':
        - 'Web Application':
          - 'OAuth/OIDC': guides/authentication/regular-webapp-oidc.md
          - 'SAML': guides/authentication/regular-webapp-saml.md
          - 'STS': guides/authentication/regular-webapp-sts.md
        - 'Mobile Application': guides/authentication/mobile-app.md
        - 'Single Page Application': guides/authentication/spa-app.md
        - 'SaaS Applications':
          - 'Google': guides/authentication/google.md
          - 'Microsoft Services':
            - 'Dynamics CRM': guides/authentication/microsoft-dynamic-crm.md
            - 'Office365': guides/authentication/office365.md
            - 'SharePoint': guides/authentication/microsoft-sharepoint.md
            - 'Workday': guides/authentication/microsoft-workday.md
          - 'Salesforce': guides/authentication/salesforce.md
          - 'Shiboleth': guides/authentication/google.md
      - 'Single Sign On': guides/authentication/enable-single-sign-on.md
      - 'Authentication Methods':
        - 'X509': guides/authentication/x509.md
        - 'IWA': guides/authentication/iwa.md
      - 'Multifactor Authentication':
        - 'Overview': guides/mfa/overview.md
        - '2FA with FIDO': guides/mfa/2fa-fido.md
        - '2FA with TOTP': guides/mfa/2fa-totp.md
        - '2FA with SMS OTP': guides/mfa/2fa-sms-otp.md
        - '2FA with Email OTP': guides/mfa/2fa-email-otp.md
        - '3FA': mfa/3fa-basic-fido-biometrics.md
      - 'Adaptive Authentication': 
        - 'Configure Adaptive Authentication': guides/configure-adaptive-auth.md
        - 'Using Function Library': guides/adaptive-auth-with-function-lib.md
      - 'Federation':
        - guides/federation.md
      - 'Access Delegation' : 
        - 'Overview': guides/access-delegation/overview.md
        - 'Configure OAuth Grant Types': guides/access-delegation/oauth-grant-types.md
        - 'Configure Refresh Token Grant': guides/access-delegation/configure-refresh-token.md
      - 'Authorization' : guides/authorization/overview.md
      - 'User Management':
          - 'Onboarding Users':
              - 'Overview': guides/user-mgt/user-onboarding-overview.md
              - 'Connecting a Userstore':
                  - 'Connecting a Database Userstore': guides/user-mgt/connect-database-userstore.md
                  - 'Connecting a LDAP Userstore': guides/user-mgt/connect-ldap-userstore.md
                  - 'Connecting a Active Directory Userstore': guides/user-mgt/connect-active-directory-userstore.md
              - 'Importing users from a file': guides/user-mgt/user-bulk-import.md
              - 'Enabling Self Sign Up': guides/user-mgt/user-sign-up.md
          - 'Managing Roles': guides/user-mgt/managing-roles.md
          - 'Managing User Accounts':
              - 'Overview': guides/user-mgt/manage-users-overview.md
              - 'Adding users from portal': guides/user-mgt/user-add.md
              - 'View and Update Profile': guides/user-mgt/user-view-profile.md
              - 'Assign Roles': guides/user-mgt/user-assign-role.md
              - 'Change Password': guides/user-mgt/change-password.md
              - 'Locking and Unlocking': guides/user-mgt/user-lock-account.md
          - 'Password Policies':
              - 'Overview': guides/user-mgt/password-policy-overview.md
              - 'Password complexity': guides/user-mgt/password-complexity.md
              - 'Password history': guides/user-mgt/password-history.md
              - 'Password expiration': guides/user-mgt/password-expiration.md
          - 'Using workflows': guides/user-mgt/configuring-workflows.md
  - 'Extend':
    - 'Authentication Script API': develop/authentication-script-reference.md
    - 'Configuration Catalog': develop/configuration-catalog.md
  - 'Deploy':
    - 'Deploy': deploy/deploying-wso2-identity-server.md
    - 'choose your model': deploy/choose-your-model.md
  - 'APIs':
    - 'REST API Reference': apis/rest-api-reference.md
  - 'Concepts':
      - 'User Management': concepts/user-management.md
      - 'Authentication':
          - 'Introduction': concepts/authentication/intro-authentication.md
          - 'Authentication Protocols':
                  - 'Introduction': concepts/authentication/intro-protocols.md
                  - 'OIDC':
                          - 'Introduction': concepts/authentication/intro-oidc.md
                          - 'OIDC Client Profiles':
                                    - 'Introduction': concepts/authentication/intro-profiles.md
                                    - 'Basic Client Profile': concepts/authentication/basic-client-profile.md
                                    - 'Implicit Profile': concepts/authentication/implicit-client-profile.md
                                    - 'Hybrid Profile': concepts/authentication/hybrid-client-profile.md
                          - 'OIDC Tokens': concepts/authentication/id-token.md
                          - 'End-User Authentication':
                                    - 'Overview': concepts/authentication/end-user-authentication.md
                                    - 'Request Object': concepts/authentication/request-object.md
                          - 'User Information': concepts/authentication/user-information.md
                          - 'Scopes And Claims': concepts/authentication/scopes-claims.md
                          - 'JWKS': concepts/authentication/jwks.md
                          - 'Discovery': concepts/authentication/discovery.md
                          - 'Session Management and Logout': concepts/authentication/session-management.md
                          - 'OIDC Device Flow': concepts/authentication/device-flow.md
                          - 'Parameter Catalogue': concepts/authentication/oidc-parameter-catalog.md
                          - 'Security Considerations': concepts/authentication/security-considerations.md
                  - 'SAML':
                          - 'Introduction': concepts/authentication/saml.md
                  - 'WS-Federation':
                          - 'Introduction': concepts/authentication/ws-federation.md
                  - 'WS-Trust':
                          - 'Introduction': concepts/authentication/ws-trust.md
                  - 'NTLM':
                          - 'Introduction': concepts/authentication/ntlm.md
                  - 'Kerberos':
                          - 'Introduction to Kerberos': concepts/authentication/kerberos.md
          - 'Adaptive Authentication': concepts/authentication/adaptive-auth.md
          - 'Multi Factor Authentication': concepts/authentication/mfa.md
      - 'Authorization':
          - 'Introduction': concepts/authorization/intro-authorization.md
          - 'Authorization Protocols':
                        - 'OAuth2':
                                    - 'Introduction': concepts/authorization/intro-oauth2.md
                                    - 'OAuth 2.0 Client Types': concepts/authorization/client-types.md
                                    - 'Grant Types':
                                          - 'Overview': concepts/authorization/grant-types.md
                                          - 'Authorization Code Grant Type': concepts/authorization/authorization-code.md
                                          - 'Implicit Grant Type': concepts/authorization/implicit.md
                                    - 'Extended Grant Types': concepts/authorization/extended-grant-types.md
                                    - 'Tokens':
                                          - 'Overview': concepts/authorization/overview.md
                                          - 'Access Tokens': concepts/authorization/access-token.md
                                          - 'Refresh Tokens': concepts/authorization/refresh-token.md
                                    - 'Client Authentication': concepts/authorization/client-authentication.md
                                    - 'Token Introspection': concepts/authorization/intorspection.md
                                    - 'DCR': concepts/authorization/dcr.md
                                    - 'Parameter Catalog': concepts/authorization/oauth2-parameter-catalog.md
                        - 'XACML':
                                    - 'Introduction to XACML': concepts/authorization/xacml.md
                        - 'UMA':
                                    - 'Introduction to UMA': concepts/authorization/uma.md
      - 'Single Sign On':
          - 'Introduction': concepts/intro-sso.md
          - 'Inbound SSO': concepts/inbound-sso.md
          - 'Outbound SSO': concepts/outbound-sso.md
      - 'Identity Federation': concepts/identity-federation.md
      - 'Identity Provisioning':
          - 'Introduction': concepts/intro-provisioning.md
          - 'Provisioning Framework': concepts/provisioning-framework.md
          - 'Inbound Provisioning': concepts/inbound-provisioning.md
          - 'Outbound Provisioning': concepts/outbond-provisioning.md
          - 'GIT Provisioning': concepts/git-provisioning.md
      - 'Consent Management': concepts/consent-management.md
      - 'Identity Anti-Patterns': concepts/identity-anti-patterns.md
      - 'Identity Bus': concepts/identity-bus.md
      - 'Comparisions':
                - 'OAuth2 vs OIDC vs SAML': concepts/oauth-oidc-saml.md
                - 'NTLM vs Kerberos': concepts/ntlm-kerberos.md
                - 'WS-Federation vs WS-Trust': concepts/federation-trust.md
                - 'SSO vs Identity Federation': concepts/sso-vs-federation.md
      - 'Compliance':
          - 'GDPR': concepts/gdpr.md
          - 'eIDAS': concepts/eidas.md
  - 'Samples':
    - samples/overview.md
    - 'Authentication':
      - 'Android': samples/android.md
      - 'iOS': samples/ios.md
      - 'Angular': samples/angular.md
      - 'React': samples/react.md
      - 'Java': samples/java.md
      - 'NodeJs': samples/nodejs.md
      - 'OpenID Connect': samples/regular-webapp-oidc-sample.md
      - 'SAML': samples/regular-webapp-saml-sample.md
    - 'Single Sign On':
      - 'OAuth/OIDC Apps': samples/sso-for-oidc-apps.md
      - 'SAML Apps': samples/sso-for-saml-apps.md
      - 'Different Authentication Protocols': samples/cross-protocol-sso.md
    - 'Multi-Factor Authentication': samples/mfa-sample.md
    - 'Adaptive Authentication':
      - 'Role-Based': samples/role-based-adaptive-auth.md
      - 'User Age-Based': samples/age-based-adaptive-auth.md
      - 'Tenant-Based': samples/tenant-based-adaptive-auth.md
      - 'User Store-Based': samples/user-store-based-adaptive-auth.md
      - 'IP-Based': samples/ip-based-adaptive-auth.md
      - 'Device-Based': samples/device-based-adaptive-auth.md
      - 'Login Attempts-Based': samples/login-attempts-based-adaptive-auth.md
      - 'ACR-Based': samples/acr-based-adaptive-auth.md
      - 'Using Function Library': samples/adaptive-auth-with-function-lib-sample.md
      - 'Limiting Active User Sessions': samples/limiting-active-sessions-adaptive-auth.md
  - 'OAuth 2.0/Open ID Connect Playground':
      - 'Authorization Code Grant': samples/auth-code-playground.md
      - 'Implicit Grant': samples/implicit-playground.md
      - 'Client Credentials Grant': samples/client-credentials-playground.md
      - 'Password Grant': samples/password-playground.md
  - 'Pickup Samples':
      - 'Pickup Dispatch OIDC': fragments/pickup-dispatch-oidc.md
      - 'Pickup Dispatch SAML': fragments/pickup-dispatch-saml.md
      - 'Pickup Manager OIDC': fragments/pickup-manager-oidc.md
      - 'Pickup Manager SAML': fragments/pickup-manager-saml.md
  - 'Configure Authentication':
    - 'Register an Application': fragments/register-a-service-provider.md
    - 'OAuth/OIDC':
      - 'Basic' : fragments/oauth-app-config-basic.md
      - 'Advanced' : guides/authentication/oauth-app-config-advanced.md
      - 'Client Configurations':
        - 'Regular OAuth/OIDC Application' : fragments/configure-client-regular-oidc-app.md
        - 'SPA Application' : guides/authentication/configure-client-spa.md
        - 'Mobile Application' : guides/authentication/configure-mobile-app.md
        - 'OIDC Logout' : fragments/oidc-logout.md
        - 'OIDC Session Management' : fragments/oidc-session-management.md
    - 'SAML':
      - 'Basic' : fragments/saml-app-config-basic.md
      - 'Advanced' : guides/authentication/saml-app-config-advanced.md
      - 'Client Configurations':
        - 'SAML Application' : fragments/configure-client-regular-saml-app.md
        - 'Retrieve User Information to the Client Application' : fragments/get-user-information-to-the-saml-application.md
  - 'Configure Authenticators':
    - 'FIDO Configurations': guides/mfa/fido-config-advanced.md
    - 'EMail OTP Configurations': guides/mfa/email-otp-config-advanced.md
    - 'SMS OTP Configurations': guides/mfa/sms-otp-config-advanced.md
    - 'TOTP Configurations': guides/mfa/totp-config-advanced.md
  - 'Admin Portal':
      - 'Applications':
          - admin-portal/applications/overview.md
          - 'Create New Application':
            - admin-portal/applications/new-application.md
            - 'Single Page Application': admin-portal/applications/add/spa.md
            - 'OIDC Web Application': admin-portal/applications/add/oidc.md
            - 'SAML Web Application': admin-portal/applications/add/saml.md
          - 'Edit Application' :
            - 'Single Page Aplication': admin-portal/applications/edit-spa.md
            - 'OIDC Web Application': admin-portal/applications/edit-oidc.md
            - 'SAML Web Application': admin-portal/applications/edit-saml.md
  - '': page-not-found.md

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs

# Extra
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  site_version: new_restructure

  nav_list:
    - Home
    - Quick Starts
    - Guides
    - Extend
    - Deploy
    - APIs
    - Concepts
