blank_issues_enabled: false
contact_links:
  - name: Report an issue
    url: https://github.com/wso2/product-is/issues/new?assignees=&labels=docs&projects=&template=doc_issues.md
    about: Click 'Open' to continue. You will be creating the new issue in the 'product-is' repo.